### ISSUE TITLE
Typing certain phrases produces unwanted emojis

### ISSUE THREAD

**Issue by terminal29** [philatype/Sen#6]
Not sure if this is an easter egg but typing any words with tantan in them ie. 'Instantaneous' makes a smiley face.

SS from [https://fonts.google.com/specimen/Sen](https://fonts.google.com/specimen/Sen):
![image](https://user-images.githubusercontent.com/20899505/76767846-f7c0c980-67e5-11ea-9626-7ff163e6c123.png)

Great font otherwise.

**Comment by Sam-Apostel** [comment]
as this is defined in the code, this is likely an inside joke/easter egg

whiteSmilingface @ [UFOs/Sen-Regular.ufo/glyphs/whiteS_milingF_ace.glif](https://github.com/philatype/Sen/blob/master/UFOs/Sen-Regular.ufo/glyphs/whiteS_milingF_ace.glif)
substituting code:
       `sub k o s a l by whiteSmilingFace;`
	`sub t a n t a n by whiteSmilingFace;`
	`sub s t a r l e e by whiteSmilingFace;`
	`sub colon D by whiteSmilingFace;`
@ [UFOs/Sen-Regular.ufo/features.fea](https://github.com/philatype/Sen/blob/master/UFOs/Sen-Regular.ufo/features.fea)

as far as I can tell, this is the mirrored smiley from the album art of [not even once by approaching nirvana](https://music.approachingnirvana.com/album/not-even-once).

**Comment by account00001** [comment]
I made a [fork](https://github.com/account00001/Sen) to remove these 'easter eggs' (except for ':D'). As great as they are, my use case can't have smileys show up for words like 'instantaneous.' Unfortunately, I don't think I can upload to Google Fonts, but you can still use locally like [so](https://stackoverflow.com/a/24990647/9504862):

```css
@font-face {
  font-family: 'Sen';
  src: url('fonts-path/Sen-Regular.eot'); /* IE9 Compat Modes */
  src: url('fonts-path/Sen-Regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('fonts-path/Sen-Regular.woff') format('woff'), /* Modern Browsers */
       url('fonts-path/Sen-Regular.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('fonts-path/Sen-Regular.svg#Sen') format('svg'); /* Legacy iOS */
}
```
Just replace `fonts-path` with the path to these fonts. Although this removed the smileys for me, I didn't test each font one by one so apologies if there are errors.
